"""autogenerated by genmsg_py from ArmJoint.msg. Do not edit."""
import roslib.message
import struct


class ArmJoint(roslib.message.Message):
  _md5sum = "80ec25bfd8132db0b162e7889fd21d62"
  _type = "packbot_ros/ArmJoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# name of the joint
string joint
# the numerical id of the joint
uint16 joint_id
# position of the joint
# unit - radian
float64 position
# velocity of the joint
# unit - radian per second
float64 velocity

"""
  __slots__ = ['joint','joint_id','position','velocity']
  _slot_types = ['string','uint16','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       joint,joint_id,position,velocity
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(ArmJoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.joint is None:
        self.joint = ''
      if self.joint_id is None:
        self.joint_id = 0
      if self.position is None:
        self.position = 0.
      if self.velocity is None:
        self.velocity = 0.
    else:
      self.joint = ''
      self.joint_id = 0
      self.position = 0.
      self.velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self.joint
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_H2d.pack(_x.joint_id, _x.position, _x.velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.joint = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.joint_id, _x.position, _x.velocity,) = _struct_H2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self.joint
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_H2d.pack(_x.joint_id, _x.position, _x.velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.joint = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.joint_id, _x.position, _x.velocity,) = _struct_H2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_H2d = struct.Struct("<H2d")
